services:
  - type: web
    name: culturewave-node-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: ONBOARDING_OTP_PEPPER
        generateValue: true
      - key: EMAILJS_SERVICE_ID
        value: service_esppdwf
      - key: EMAILJS_PUBLIC_KEY
        value: PDb2vpOIeLkbZBBFP
      - key: EMAILJS_ONBOARDING_OTP_TEMPLATE_ID
        value: template_8ho2pwf
